### ISSUE TITLE
Arxiv spec wrong type

### ISSUE THREAD

**Issue by mindrones** [nestauk/dapsboard#146]
fails: https://dapsboard-dev.netlify.app/builder/?q=(dataset:general_arxiv_v0,form:primary,forms:!((name:primary,selection:(aggregation:missing,field:type_of_entity,type:ES_text_w_keyword)),(name:secondary)),size:0)

works: https://dapsboard-dev.netlify.app/builder/?q=(dataset:general_arxiv_v0,form:primary,forms:!((name:primary,selection:(aggregation:missing,field:url_of_article,type:ES_text_w_keyword)),(name:secondary)),size:0)

Seems like a bug in the specs

**Comment by saabi** [comment]
Related:
https://dapsboard-dev.netlify.app/builder?q=(dataset:arxlive_arxiv_v3,form:primary,forms:!((name:primary,selection:(aggregation:missing,field:id_digitalObjectIdentifier_article)),(name:secondary)),size:0)
