### ISSUE TITLE
Deselecting the dataset throws an error

### ISSUE THREAD

**Issue by mindrones** [nestauk/dapsboard#41]
Once we created a working query, by unselecting the dataset we get an error and it's then impossible to re-select it.

<img width="896" alt="Screenshot 2020-06-04 at 11 24 42" src="https://user-images.githubusercontent.com/1309648/83802753-41150c80-a6a3-11ea-81ce-6be0c21cc818.png">

**Comment by saabi** [comment]
After disabling autoloading-on-select and unselecting the dataset, `readyForRequest` remains true and should be 'false' at this point.

The `Execute` button is disabled directly by this property and remains enabled. This means it's probably querying with the almost empty `{size:0}`
