### ISSUE TITLE
Add GtR spec

### ISSUE THREAD

**Issue by mindrones** [nestauk/dapsboard#52]
See https://github.com/nestauk/nesta/pull/286#issuecomment-653162602 and #75

**Comment by saabi** [comment]
Typescript type definitions will be slightly different for ElasticSearch v7 datasets so this will require managing typing versions as well and selecting these based on `api_version` in the dataset specs.

https://github.com/nestauk/dapsboard/blob/51a78c2615368febdee971754c0c8beb4933abae/src/node_modules/app/elasticsearch/typings/dsl.ts#L111
