### ISSUE TITLE
Aggs parameters defaults

### ISSUE THREAD

**Issue by mindrones** [nestauk/dapsboard#80]
We need to have some defaults, to avoid unneeded/empty elements in the response.

Here's a histogram with no `min_doc_count`:

<img width="1165" alt="Screenshot 2020-09-22 at 18 51 51" src="https://user-images.githubusercontent.com/1309648/93918814-ced54000-fd04-11ea-9b1c-6ba4bd1e133f.png">

Here's the same histogram with `min_doc_count: 1`:

<img width="1204" alt="Screenshot 2020-09-22 at 18 51 40" src="https://user-images.githubusercontent.com/1309648/93918803-caa92280-fd04-11ea-9f55-c07052c57696.png">

**Comment by mindrones** [comment]
Some fields have indeed an ES default, applied if we don't supply a value, see below.
We could gather these values from the doc and make them specific, so that the user sees the value in the field as a placeholder, maybe styled differently (e.g. the input background being `palegreen`).

<img width="1677" alt="Screenshot 2020-09-24 at 12 02 52" src="https://user-images.githubusercontent.com/1309648/94137465-56829200-fe5e-11ea-9d28-f42dc3870428.png">

https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-aggregations-bucket-diversified-sampler-aggregation.html: `The default setting for max_docs_per_value is 1.`

**Comment by saabi** [comment]
The default value of  the `collect_mode` parameter in the `terms` aggregation depends on the cardinality of the selected field.

> https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-aggregations-bucket-terms-aggregation.html
> The breadth_first is the default mode for fields with a cardinality bigger than the requested size or when the cardinality is unknown (numeric fields or scripts for instance). It is possible to override the default heuristic and to provide a collect mode directly in the request:
