### ISSUE TITLE
Support aggregation arguments being arrays of native values

### ISSUE THREAD

**Issue by mindrones** [nestauk/dapsboard#89]
Possibly related to #59, we need to be able to edit array parameters with items being native values (not objects or arrays).

E.g. `values` in `/builder?q=(dataset:mosaic_nih_v7,form:primary,forms:!((name:primary,params:(values:%27%27),selection:(aggregation:percentile_ranks,field:cost_total_project,type:integer))),size:0)`

**Comment by saabi** [comment]
Here's a summary of aggregations that use parameters with arrays or objects.

### Metric Aggregations

* percentiles
  * hdr: object with single property `number_of_significant_value_digits`
* top_hits
  * sort: SortOptions object
  * _source: SourceOptions object
* top_metrics
  * metric: polymorphic: MetricAggregation | MetricAggregation[]
  * sort: SortOptions object
* weighted_avg: (Needs two field selections)
  * value: MetricAggregation
  * weight: MetricAggregation
  * format: Object, shape unknown
  * value_type: Object, shape unknown

### Bucket Aggregations

* filter and filters: Seems to require understanding of most ES querying capabilities such as `match` and `term`
* adjacency_matrix
  * filters: Seems to use the same querying capabilities used in the above aggreation type
* composite
  * sources: List of objects that are themselves a limited form of aggregation queries
* date_range
  * ranges: multi prop object `{to:'...', from: '...'}` specifying ranges
* geo_distance
  * ranges: list of range objects specifying distances  `{to: number, from: number}`
* ip_ranges: list of range objects specifying distances  `{to:'0.0.0.0', from: '0.0.0.0'}`
* range: list of range objects specifying distances  `{to: number, from: number}`
* significant_terms:
  * background_filter: object with single property `term` (type ???)
  * jlh: An empty object `{}` (presumably reserved for future parameters?)
  * chi_square: An empty object `{}` (presumably reserved for future parameters?)
  * gnd: An empty object `{}` (presumably reserved for future parameters?)
  * percentage: An empty object `{}` (presumably reserved for future parameters?)
  * mutual_information: object with single boolean property `include_negatives`
  * background_filter: Custom background context. Filter object format (as in non aggregation queries)

* significant_text:
  * background_filter: object with single property `term` (type ???)
  * source_fields: array of field names

Type unions of explicit strings not included above.

**Comment by saabi** [comment]
There're are some regularities in the formats suggesting that a common editor could be implented for them. For example ranges have a `from` and `to` field, but they might accept different formats and semantics in their values dependeng on the aggregation (range, date_range, ip_range)

Besides ranges, some aggrregations also support filtering, which are specified using most of the ES querying DSL besides aggregations, so supporting that in Dapsboard might be quite a bit of work.

Other object formats that are used in some aggregation parameters are subsets of the aggregation DSL itself (`sources` parameter in `composite`) and sorting parameters.

Though this conclusion applies to mostly to #59 in summary, it might be easier to provide specialized components for at least a few of these parameters (sorting, ranges and perhaps also filtering and parameters that accept aggregation queries)

**Comment by saabi** [comment]
Array editors will be needed in the form editor for:

* `percentile_rank`: needs an array of numbers in its `values` parameter
* `percentiles`: needs an array of floats in its `percents` parameter
* `terms` aggregation has `include` and `exclude` parameters which polymorphically accept either a string holding a regular expression, or an array of exact string values for matching.
* `top_metrics`: has a `metric` parameter which can be either a single field selection/configuration object or an array of these, polymorphically.
* `geo_distance`: `ranges` parameter, which will require some form of RangeEditor component.
* `range`: same as above

In addition to these, some aggregations use objects as holders of lists of named values:

* `adjacency_matrix`: `filters` takes an object holding named instances of filter objects
* `composite`: the `sources` parameter can take either an array of anonymous source objects, or an object of named source objects

**Comment by saabi** [comment]
Waiting for #103 before proceeding
